### ISSUE TITLE
Include missed on attr.c

### ISSUE THREAD

**Issue by srsampson** [ka9q/ka9q-radio#1]
In attr.c it has:

```
#ifdef __linux__
#include <attr/xattr.h>
#else
#include <sys/xattr.h>
#endif
```
But on Ubuntu the include is in the ```sys``` directory. Changed to:

```
#include <sys/xattr.h>
```

Maybe other linux versions differ, which will complicate the #ifdef

**Comment by ka9q** [comment]
That's weird. The man page now says

#include <sys/types.h>

#include <sys/xattr.h>

Maybe it changed after I originally wrote attr.c. I hate this sort of 
thing. Anyway, I've made the change. Thanks for the report! --Phil

**Comment by ka9q** [comment]
well, that wasn't very hard...

**Comment by srsampson** [comment]
> well, that wasn't very hard...

I'm just glad I wasn't some special case! Thanks.
