### ISSUE TITLE
getting a serial number for an Airspy HF+

### ISSUE THREAD

**Issue by vielmetti** [ka9q/ka9q-radio#18]
The provided docs at https://github.com/ka9q/ka9q-radio/blob/main/docs/airspy.md give instructions for how to get the serial number for an Airspy device using the `airspy_info` command. 

This doesn't work if you have an Airspy HF+; instead, you need the `airspyhf_info` command, which can be found in this repo:

https://github.com/airspy/airspyhf

I found it necessary to build this from source on Debian 10 ("buster"), but it looks like there's a package for Debian 11 ("bullseye").

https://packages.debian.org/bullseye/airspyhf

Note that you may need to run the command as root.

(this took far too long to figure out on my own, so the hope is that an issue here will contribute to the next person along the way).

**Comment by ka9q** [comment]
Thanks! I'll add that to airspy.md.

Maybe I should write something to help you create the airspy/airspyhf 
config files that will read the serial numbers directly so you won't 
have to use their utility programs.

OTOH, you already need their libraries, and the commands aren't hard to 
install along with them.

I've been thinking about merging airspyhfd into airspyd so only one is 
needed to handle both types of devices. They already use a common config 
file (/etc/radio/airspyd.conf). I'll ruminate on this.

Phil
