### ISSUE TITLE
Compile error on Ubuntu

### ISSUE THREAD

**Issue by berrySkies** [ka9q/ka9q-radio#39]
Hi, Just tried to install ka9q-radio for first time on a Ubuntu system. See attached screenshot for make error messages. 
![Screenshot 2023-09-09 141014](https://github.com/ka9q/ka9q-radio/assets/5278164/9c0806e7-3693-4244-a84d-82ce695b18f5)

Thanks for any assistance. 
Regards Alan VK2ATW

**Comment by ka9q** [comment]
Ah, I caught that one myself and fixed it last night. Getting all the #includes right can be a problem. On some systems, one include file may automatically include the one you need, masking the fact that you didn't include it explicitly. And it may compile on some systems and not others.

**Comment by berrySkies** [comment]
Thanks Phil and THANKYOU for making the software available. I'm looking forward to learning it's use and experimenting. Best wishes from down under. Alan
