### ISSUE TITLE
Build error - Makefile.linux missing wspr-decoded

### ISSUE THREAD

**Issue by lukyduck** [ka9q/ka9q-radio#44]
Trying to compile and install on Ubuntu 22.04  I get a Make error that wspr-decoded is not found (but it is specified in the EXECS line). It looks like this may be in state of flux, as I see comments that wspr-decoded was merged with jt-decoded. 

Is there a needed update in the Makefile.linux?
Can I just remove the wspr-decoded from EXECS?

Excuse me if I am just not understanding the Makefile. No expert in that area

73,

Tom, KG3V

**Comment by lukyduck** [comment]
This has clearly been addressed in the latest Makefiles, so this can be CLOSED. No need to waste your time.

The radio package works nicely with Airspy-hf on my laptop running UBUNTU 22.04

73,
Tom, KG3V

**Comment by ka9q** [comment]
Glad it works!
