### ISSUE TITLE
"tune" command line argument support

### ISSUE THREAD

**Issue by azwirko** [ka9q/ka9q-radio#48]
Hi Phil

  Could you please add "low" and "high" cut support command line options for the "tune" command.  These are available in the radiod.conf file, but I don't see a way to change them on the fly.  

  To support my band/mode hopping in QRA-Skimmer I apparently need that to tune in WSPR correctly.  Otherwise I've got "tune" working great in my app scheduler to band/mode hop between FT4 & FT8 and other 3 KHz wide modes.

73

andyz - K1RA

p.s. - thanks for the shout out in your TAPR DCC 2023 presentation

**Comment by ka9q** [comment]
Done! Use the -L and -H (or --low and --high) options. If low > high, they will be swapped.
