### ISSUE TITLE
Support for SDRplay

### ISSUE THREAD

**Issue by ke5gdb** [ka9q/ka9q-radio#61]
It looks like some amazing work has been done by Franco over at https://github.com/fventuri/ka9q-radio/tree/sdrplay to add support to the SDRplay. Would y'all entertain a PR to merge this in with the main branch?

73 de KE5GDB

**Comment by ke5gdb** [comment]
Another option may be libmirisdr-5: https://github.com/ericek111/libmirisdr-5

This may be a workaround for the previously discussed issues with the SDRplay API licensing BS.

**Comment by cmh716** [comment]
Was Franco's code already added here?  https://github.com/ka9q/ka9q-radio/commit/611956ccadc6263364ffb653c5533c03d9910d84

I have not personally tested this.

**Comment by ke5gdb** [comment]
It was, but it looks like the architecture changed from each radio type having a unique daemon to a single radiod daemon. When this change happened, SDRplay support was dropped.
