### ISSUE TITLE
PSKreporter FT8 spots with invalid or incorrect frequency

### ISSUE THREAD

**Issue by waterwin** [ka9q/ka9q-radio#77]
After my last git pull of wsprdaemon for my RX888 I noticed the FT8 spots being reported without or with a wrong frequency. Just as 1 example, I am showing the contents of my ft8.log file and the general spots for that FT8 Tx on pskreporter.

	Line 3681: 2024/12/17 14:31:00  18 +1.20 14,505.2 ~ CQ UR4SXA KN28
	Line 3686: 2024/12/17 14:32:30  16 +1.20 14,505.2 ~ CQ UR4SXA KN28

From correct spots on pskreporter
Tx UR4SXA Loc KN28
Last Tx at Tue, 17 Dec 2024 14:40:59 GMT
Last frequency: 3.574.019 MHz (80m), FT8

On pskreporter the result is that all (my) FT8 spots marked n1dq-importer-ka9q-radio are grey and do not have frequency information.

So I stopped the ft8-decoder.service for the moment.

**Comment by ka9q** [comment]
Yeah, it takes the frequency from the SSRC passed in the radiod config file. It takes all the digits as a string, removes any gkm characters, and uses that as a frequency in Hz. Pad out the frequency with enough trailing zeroes to bring it to a hz and the frequencies should be correct, e.g, 14m074000. Encoding the frequency in the SSRC is a kludge I am working to eliminate; soon the decoders will extract it from the channel status messages so the SSRC can be arbitrary.
